select * from customer_shopping limit 20

--total revenu generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue 
from customer_shopping
group by gender

--Which customer used a discount but still spent more than the avg purchase amount?
select customer_id , purchase_amount 
from customer_shopping 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer_shopping)

--Which are the top 5 products with the highest avg review rating
select 
	item_purchased, 
	ROUND(AVG(review_rating)::numeric, 2) as "Avg Product Rating"
from customer_shopping
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Comparing the avg purchase amount between standard and express shipping
select shipping_type ,ROUND(AVG(purchase_amount),2)
from customer_shopping
where shipping_type in ('Standard','Express')
group by shipping_type;

--Do subscribed customer spen more?
--Compare avg spend and total revenue b/w sub and non-sub
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer_shopping
group by subscription_status
order by total_revenue,avg_spend desc;

--Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) ,2) as discount_rate
from customer_shopping
group by item_purchased
order by discount_rate desc
limit 5;

--Segmnet customers into New,Returning and Loyal based on their total number of 
-- previous purchases, and show the count of each segment.
with customer_type as(
select customer_id, 
previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment 
from customer_shopping)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

--What are the top 3 purchased products within each category?
with item_counts as(
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(
	partition by category 
	order by count(customer_id) DESC) 
AS item_rank
from customer_shopping
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts 
where item_rank <= 3;

--Are customer who are repeat buyers(more then 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping
where previous_purchases >  5
group by subscription_status

--What is the revenue contribution of each age gropu?
select age_group,
SUM(purchase_amount) as total_revenue
from customer_shopping
group by age_group
order by total_revenue desc;